name: iOS starter workflow

on: 
  workflow_dispatch:
  
env:
    TEST: "123"
    
jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: self-hosted

    steps:
      - name: Checkout sourse code
        uses: actions/checkout@v3
    
      - name: Build and Test iOS App
     
        run: |
          env
      - name: Run tests
        run: |
           pwd
