name: iOS starter workflow

on: 
  workflow_dispatch:
  
env:
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
    OS-latest: 'macos-12'
    
jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: self-hosted

    steps:
      - name: Checkout sourse code
        uses: actions/checkout@v3
      
      - name: Setup ruby env
        uses: actions/setup-ruby@v1.139.0
        with:
          ruby-version: '3.2.1'
          ImageOs: 'macos-12'
        
      - name: Install Fastlane
        run: |
          bundle install
          
      - name: Install & update Fastlane plagin
        run: |
         bundle exec fastlane install_plugins
         bundle exec fastlane update_plugins
                  
      - name: Build and Test iOS App
        run: |
          bundle exec fastlane ios build
          
      - name: Run tests
        run: |
         bundle exec fastlane ios tests
         

      - name: Save test report
        uses: actions/upload-artifact@v3
        with:
          name: Test report
          path: ./Build/SimpleCalculator.xresult
          retention-days: 7
